# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/filip/Downloads/Basys3_Basic_Demo_1/Basys3_Basic_Demo_1.cache/wt [current_project]
set_property parent.project_path C:/Users/filip/Downloads/Basys3_Basic_Demo_1/Basys3_Basic_Demo_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/MouseCtl.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/MouseDisplay.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/Ps2Interface.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/UART_TX_CTRL.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/clk_wiz_0.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/clk_wiz_0_clk_wiz.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/debouncer.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/vga_ctrl.vhd
  C:/Users/filip/Downloads/Basys3_Basic_Demo_1/GPIO_Demo.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/filip/Downloads/Basys3_Basic_Demo_1/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/filip/Downloads/Basys3_Basic_Demo_1/Basys3_Master.xdc]


synth_design -top GPIO_demo -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef GPIO_demo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file GPIO_demo_utilization_synth.rpt -pb GPIO_demo_utilization_synth.pb"
